server:
  name: go-echo-sql-sample
  port: 8080

sql:
  driver: postgres
  data_source_name: postgres://postgres:abcd1234@localhost/masterdata?sslmode=disable

log:
  level: info
  map:
    time: "@timestamp"
    msg: message
    caller: caller
    function: func

middleware:
  log: true
  skips: /health
  request: request
  response: response
  duration: duration
  size: size

response:
  id: X-Response-Id
  correlation: X-Correlation-Id