server:
  name: go-echo-sql-tutorial
  port: 8080

sql:
  driver: postgres
  data_source_name: postgres://qtqyqrzg:4-fPQ7h10SZk3d6_AkaxSGZ5AjZ6RdWO@satao.db.elephantsql.com/qtqyqrzg

log:
  level: info
  map:
    time: "@timestamp"
    msg: message
    stacktrace: stacktrace
    caller: caller
    function: func

middleware:
  log: true
  skips: /health
  request: request
  response: response
  duration: duration
  size: size
  masks: mobileNo,creditCard
  constants:
    app_id: "123"
    service: payment
  map:
    mobile_no: header.mobileNo
    credit_card: header.creditCard
    corr_id: header.corrId
    email: body.email
    username: body.username

response:
  id: X-Response-Id
  correlation: X-Correlation-Id